name: TestDriver.ai / Generate / Explore

permissions:
  actions: read
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: |
            1. /run testdriver/onboarding.yml false false
            2. /generate desktop 10
          prerun: |
            Get-NetIPAddress -AddressFamily IPv6
            # URL for the Arc browser installer
            $installerUrl = "https://releases.arc.net/windows/ArcInstaller.exe"
            # Location to save the installer
            $installerPath = "$env:USERPROFILE\Downloads\ArcInstaller.exe"
            # Download the Arc browser installer
            Write-Host "Downloading Arc browser installer..."
            Invoke-WebRequest -Uri $installerUrl -OutFile $installerPath
            # Check if the download was successful
            if (Test-Path $installerPath) {
                Write-Host "Download successful. Running the installer..."
                Start-Process -FilePath $installerPath -ArgumentList '/silent' -Wait
                Start-Sleep -Seconds 10
            } else {
                Write-Host "Failed to download the Arc browser installer."
            }
            
            # Replace placeholder email with generated
            (gc ./testdriver/onboarding.yml) -replace "placeholder@testdriver.ai", '${{ github.run_id }}.${{ github.run_attempt }}@testdriver.ai' | sc -Force ./testdriver/onboarding.yml
          create-pr: true
          pr-title: "TestDriver.ai / Generate Test Plans"
          pr-branch: testdriver/generate-${{ github.run_id }}-${{ github.run_attempt }}
        env:
          FORCE_COLOR: "3"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}